webtalk_init -webtalk_dir C:/Users/jtsoo/SooHooCPE133Lab7/SooHooCPE133Lab7.sim/sim_1/behav/xsim/xsim.dir/Problem1FSMSequencer_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 10 22:32:13 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8e53445f-3800-4ed0-b2f4-0048750dbe4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "82fcd0f69fe74943b9d9a92d0fa6dce1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.56_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14608_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2426709391 -regid "" -xml C:/Users/jtsoo/SooHooCPE133Lab7/SooHooCPE133Lab7.sim/sim_1/behav/xsim/xsim.dir/Problem1FSMSequencer_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jtsoo/SooHooCPE133Lab7/SooHooCPE133Lab7.sim/sim_1/behav/xsim/xsim.dir/Problem1FSMSequencer_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jtsoo/SooHooCPE133Lab7/SooHooCPE133Lab7.sim/sim_1/behav/xsim/xsim.dir/Problem1FSMSequencer_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
